version: 0.2

  #env:
  #variables:
  # key: "value"
  # key: "value"
  #parameter-store:
  # key: "value"
  # key: "value"
  #secrets-manager:
  # key: secret-id:json-key:version-stage:version-id
  # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
  # - variable
  # - variable
  #git-credential-helper: yes
  #batch:
  #fast-fail: true
#build-list:
#build-matrix:
#build-graph:
phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      #      - echo "installing terraform"
      #      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_arm64.zip
      #      - unzip terraform_1.5.7_linux_arm64.zip
      #      - ls -l
      #      - mv terraform /usr/local/bin
      #      - chmod a+x /usr/local/bin/terraform
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform version
  build:
    commands:
      - terraform init
      - terraform apply -auto-approve


